spring:
  application:
    name: customer-service
  cloud:
    config:
      discovery:
        enabled: true
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: swapi-spring-webflux
    version: 0.0.4-SNAPSHOT

server:
  port: 8080
  error:
    whitelabel:
      enabled: true

logging:
  level:
#    web: DEBUG
    com.exampl: DEBUG

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
