spring:
  application:
    name: customer-service
  cloud:
    config:
      discovery:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    enabled: false

greeting:
  phrase: Hi